name: Build Electron App for macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual triggering

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Use the latest Node.js LTS version
          cache: "npm"

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci  # Clean install dependencies

      # Build the application
      - name: Build application
        run: |
          npm run build

      # Package the Electron app for macOS
      - name: Package Electron app
        run: |
          npm run build:mac  # Adjust this to match your packaging script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Create a release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') # Only create release for tags
        with:
          files: |
            dist/*.dmg
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-electron-app
          path: |
            dist/*.dmg
            dist/*.zip
          retention-days: 5
